 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/movies", type: :request do
  
  category = Category.first_or_create!(title: 'Comedy')

  # Movie. As you add validations to Movie, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do 
    {
      :title => 'Title',
      :category_ids => category.id
    }
  end

  let(:invalid_attributes) do 
    {
      :title => '',
      :category_ids => category
    }
  end

  describe "GET /index" do
    it "renders a successful response" do
      Movie.create! valid_attributes
      get movies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      movie = Movie.create! valid_attributes
      get movie_url(movie)
      expect(response).to be_successful
    end
  end

end
